### ISSUE TITLE
Can't build and test

### ISSUE THREAD

**Issue by zSkull162** [RiskiVR/RiskiPlayer#2]
Trying to build and test gives this error:

![Screenshot 2022-04-29 195146](https://user-images.githubusercontent.com/70001936/166081849-471d35a4-2bde-4094-af72-c349617d59e7.png)

I made sure I did everything right, so i think it's just a bug with Riskiplayer 2.1

**Comment by RiskiVR** [comment]
Did you import UdonSharp before importing the video player?

**Comment by zSkull162** [comment]
Yes, I also tried re-downloading UdonSharp and the videoplayer, but it still gave that error.

**Comment by RiskiVR** [comment]
Did you already have USharpVideo installed?

**Comment by zSkull162** [comment]
No, I did not.

**Comment by RiskiVR** [comment]
Hello, turns out the v2.1 package was incorrectly exported. v2.2 is released now with everything fixed and functional
