### ISSUE TITLE
Unable to Build&Test

### ISSUE THREAD

**Issue by zSkull162** [RiskiVR/RiskiPlayer#3]
I followed everything I usually do, which is import UdonSharp first, then Riskiplayer, and I recently tried 2.2 instead of 2.0, and 2.2 gave me this error, and didn't allow me to build and test
![Screenshot 2022-08-14 154203](https://user-images.githubusercontent.com/70001936/184552397-15f8a4d4-8f4b-497e-a428-0490a3f22ad6.png)
.

**Comment by SincerestBoy** [comment]
Did you ever find out what was wrong?

**Comment by zSkull162** [comment]
Nope

**Comment by RiskiVR** [comment]
Fixed in [3.0](https://github.com/RiskiVR/RiskiPlayer/releases/tag/3.0)
