### ISSUE TITLE
"The type or namespace name 'IsValid' does not exist in the namespace 'Utilities' (are you missing an assembly reference?)"

### ISSUE THREAD

**Issue by SincerestBoy** [RiskiVR/RiskiPlayer#5]
![image](https://user-images.githubusercontent.com/90456148/188799932-44f5d169-d0b0-4cd4-a9d9-f3bef81c45ff.png)
These are the errors I got.

So in the script USharpVideoPlayer it says that the type or namespace name 'IsValid' doesn't exist in the namespace 'Utilities'.
And Utilities is pretty important so it breaks everything.
Someone said that this means Unity normally breaks the SDK until I found out it wasn't actually in the SDK it was imported with RiskiPlayer.

**Comment by RiskiVR** [comment]
Fixed in [3.0](https://github.com/RiskiVR/RiskiPlayer/releases/tag/3.0)
