### ISSUE TITLE
v3.0 - Shader error, can't see the video screen.

### ISSUE THREAD

**Issue by zSkull162** [RiskiVR/RiskiPlayer#6]
Errors I get from the shader. This causes the video screen to be black when a video is playing
![image](https://github.com/RiskiVR/RiskiPlayer/assets/70001936/ff086c9c-2509-4333-938f-17d328c73854)
![image](https://github.com/RiskiVR/RiskiPlayer/assets/70001936/76185154-a7f1-48fa-b813-3df57ec99f6c)

**Comment by RiskiVR** [comment]
Will look into this

**Comment by RiskiVR** [comment]
Package was incomplete. Please redownload it, I updated the package with everything needed.
