### ISSUE TITLE
(3.0) Toggling videoplayer with menu closed causes volume/brightness to disappear

### ISSUE THREAD

**Issue by zSkull162** [RiskiVR/RiskiPlayer#7]
When the videoplayer gets turned off and on again while the menu is closed, the volume and brightness sliders won't re-appear when the menu is re-opened.
(If the videoplayer is toggled while the menu is still open, this wont happen)

https://github.com/RiskiVR/RiskiPlayer/assets/70001936/47e8fe1d-e28e-4468-9312-6b2c08c07d2c

**Comment by RiskiVR** [comment]
That's interesting. 
The objects might be somehow disabling those objects which shouldn't happen when toggled. 
I'll see if applying GameObject Active triggers in the animations helps.

**Comment by RiskiVR** [comment]
Verified + Found the issue! 
The show animation doesn't account for when the sliders move upwards, therefore they stay out of the screen when rebooted.
I'm pushing another silent patch for this release. Check the releases!
