### ISSUE TITLE
Unity Error CS0246: The type or namespace name 'Cysharp' could not be found

### ISSUE THREAD

**Issue by taskmgrTZT** [RiskiVR/RiskiPlayer#8]
I opend an new unity project with unity 2022.3.6f1. 
Then, I drop riskiplayer(v3.1) in the world, however when I click "play mod", It seem has some error.
I'm not sure, Is that I do something wrong?
![image](https://github.com/RiskiVR/RiskiPlayer/assets/99248821/8423818d-32ca-4d54-811a-9f9e9b3c3d7c)
![image](https://github.com/RiskiVR/RiskiPlayer/assets/99248821/7fa100ab-260d-46ae-bd84-d65884720dbf)

**Comment by RiskiVR** [comment]
It seems it is conflicting due to you already having ProTV Extras installed. RiskiPlayer is now bundled with ProTV Extras, so you can delete RiskiPlayer v3.1, and you can use the RiskiPlayer prefab under ProTV Extras.
