### ISSUE TITLE
Error CS0234: The type or namespace name "ProTV" does not exist in the namespace ArchiTech

### ISSUE THREAD

**Issue by AshtonSparx** [RiskiVR/RiskiPlayer#9]
![image](https://github.com/RiskiVR/RiskiPlayer/assets/53165730/4ef2a1b6-828b-45d8-903c-f54b339ef41f)
![image](https://github.com/RiskiVR/RiskiPlayer/assets/53165730/6a8e00a2-1d5a-4025-8be0-686d615832a8)
I've imported everything related to ProTV, VRChatSDK comes with UdonSharp so that doesn't need to be imported, but for some reason, it's telling me the error posted above. I'm using the latest version of RiskiPlayer (v3.1 as of posting this)

Unity 2022.3.22f1, SDK 3.6.1

How do I fix this?

**Comment by AshtonSparx** [comment]
I have found the issue, according to [ProTV documentations](https://protv.dev/start), you have to show pre-releases and Settings -> Packages -> Show Pre-Release Packages to import the actual TV stuff. I never used protv before so I didn't know this.

**Comment by RiskiVR** [comment]
Hello!

I highly recommend using RiskiPlayer from the ProTV.Extras package as it's now officially bundled with ProTV, and has been slightly updated to work better with the current version of ProTV.

Eventually I'll get to updating my download links to redirect to the official ProTV downloads.
